[build]
target = "avr-none"
#rustflags = ["-C", "target-cpu=attiny402"]
# note that we use eg the known attiny1614 to generate for the unknown avr128db28 if we specify the correct flash size to the linker:
rustflags = ["-C", "target-cpu=attiny1614", "-C", "link-args=-Wl,--defsym=__TEXT_REGION_LENGTH__=131072"]
#rustflags = ["-C", "target-cpu=attiny1614"]

[target.'cfg(target_arch = "avr")']
runner = "ravedude"

[unstable]
build-std = ["core"]
